### ISSUE TITLE
2021.11.14 [변경 예정 사항 및 버그] 

### ISSUE THREAD

**Issue by Lesin928** [m48483/SocializerRepo#101]
:black_medium_small_square: 관찰 활성화 시 돋보기 아이콘으로 변경 시 클릭되는 위치 조정
~~:black_medium_small_square: 알림창 UI 미적용~~
:black_medium_small_square: 버튼에 커서 올릴때 활성화 되는 이펙트 수정
:black_medium_small_square: 옵션창 창모드 체크박스 수정
:black_medium_small_square: 주인공 이름이 안 뜨던거 수정
~~:black_medium_small_square:  변수 DontDestroyonload로 flowchart 통해서 관리 예정(추후 변동 가능성 o)~~
~~:black_medium_small_square:  글씨 폰트 깨지는거 수정~~
~~:black_medium_small_square:  선택지 있는 팝업 문제수정 (팝업이 안 닫히는 오류)~~
:black_medium_small_square:  머지 후 미싱뜨는 이미지(구현완료 된 사항)에 이미지 재적용
:black_medium_small_square:  로딩 씬 실행 오류 해결

**Comment by horimihorimi** [comment]
◾ 변수 DontDestroyonload로 flowchart 통해서 관리 예정(추후 변동 가능성 o)
◾ 글씨 폰트 깨지는거 수정

완료했습니다.

**Comment by Lesin928** [comment]
선택지있는 팝업 문제수정 완료
