### ISSUE TITLE
2021.05.16 [프로그래머 전원]

### ISSUE THREAD

**Issue by LEI-2812** [m48483/SocializerRepo#15]
📢 마감일 : 5월 23일
◾ 7월까지의 일주일 단위 세부 계획서 제출
◾ 굳이 일주일 단위는 아니어도 되지만, 무슨 내용을 언제 할 예정인지 자세하게 기입

**Comment by LEI-2812** [comment]
화요일에 계획서 받은 이후에 이슈 닫을 예정입니다.
또한 공부 계획서가 저에게 전달되면 그때 공부 일정에 대한 이슈를 추가하도록 하겠습니다.

**Comment by m48483** [comment]
확인했습니다

**Comment by Lesin928** [comment]
확인했습니다

**Comment by horimihorimi** [comment]
확인했습니다
