### ISSUE TITLE
2021.05.23 [최희승] -인물

### ISSUE THREAD

**Issue by LEI-2812** [m48483/SocializerRepo#22]
📢 마감일 : 5월 30일
◾ 주요 npc '딜런' 완성
◾ 그래픽 회의 시간을 이용하여 기획과 색감, 표정, 구도 등을 조절할 것

**Comment by Mepalo** [comment]
확인했습니다.

**Comment by LEI-2812** [comment]
2021.05.30
◾ 작업물 지연됨
◾ 6월 20일 전까지 작업 완료할 것
