### ISSUE TITLE
2021.05.30 [이승민] - 폴더 세분화 작업

### ISSUE THREAD

**Issue by Lesin928** [m48483/SocializerRepo#27]
각자 푸쉬된 작업물이 최신화되어있는지, 없어진 파일이 있는지 확인하고 여기에 메세지를 남겨주세요.
이슈 확인하고 변동사항 없을시 문제없음. 이라고 써주시고 네명 다 써주시면 이슈 닫겠습니다

**Comment by LEI-2812** [comment]
문제없음.

**Comment by hor5085** [comment]
(로비,바,사무실,집 수정).jpg는 참고 이미지입니다. robby.jpg는 삭제 하셔도 됩니다.

**Comment by Mepalo** [comment]
확인했습니다.

**Comment by ywj58** [comment]
확인했습니다

**Comment by ywj58** [comment]
graphic 폴더에 ui폴더 생성
