### ISSUE TITLE
2021.06.06 [이승민] - 작업물 이름 변경

### ISSUE THREAD

**Issue by Lesin928** [m48483/SocializerRepo#32]
📢 마감일 : (기획) 6월 8일, 나머지 마감일 없음.
공지) 폴더 세분화와 파일상태 최신화 완료 되었습니다. 앞으로 해당 작업물에서 변경사항 있을시 파일 완전 삭제후 이름 변경하여 다시 업로드 부탁드립니다.

◾ 현재 최신화된 파일들 이름이 제각각입니다. 작업물 명명 규칙을 정해놨으니 다음 작업물 업데이트때 각자 작업물의 이름을 변경 해주시고, 추가 건의사항은 코멘트 부탁드립니다.

◾ 이름 변경 이후 커밋시에 커밋메세지를 다음과같이 작성 해주시길 바랍니다.

EX) Summary : 그래픽_UI_작업물 이름변경
Description : a, b을 a_1_1, b_2_1로 변경
형식   
-이름_버전_수정횟수

◾ 기획자께선 각 작업물 이름이 각각 명시되어 있는지 기획서 확인 후 코멘트 부탁드립니다.

◾ 명명 규칙에 대한 건의사항은 해당 이슈 코멘트로 남겨주시길 바랍니다.

+건의사항 반영 완료

**Comment by hor5085** [comment]
완료했습니다

**Comment by LEI-2812** [comment]
완료했습니다

**Comment by jjihn** [comment]
사운드, 배경, npc 작업물 모두 기획서에 맞춰 이름이 명시되어 있습니다.


**6월 7일 현재 대화창 ui 작업물의 이름이 '이름 지정 필요'로 명명되어 있지 않습니다.**
또한 ui 작업물을 합쳐서 하나로 올리지 마시고 기획서 내용에 맞춰 따로 파일을 올려주셔야 할 것 같습니다.
![예시](https://user-images.githubusercontent.com/67685616/121014217-b181cc80-c7d4-11eb-8057-07653654b954.png)
[예시 사진]
![ui](https://user-images.githubusercontent.com/67685616/121013818-49cb8180-c7d4-11eb-872f-09a286ec39dd.png)
[ui 기획서]
ui 작업자 께서는 위 예시와 ui 기획서를 참고하셔서 각 창과 버튼 파일을 기획서 내용과 일치하게 올려주시기 바랍니다.

**건의사항**
현재 작업물의 버전이 여러개인 경우, '(작업물 이름)_(버전)_(수정 순서)' 식으로 이름이 지어져 있습니다.(ex. 버튼음_01_1)
사운드나 그래픽의 경우 이름이 같아도 버전이 바뀌는 경우가 많습니다.
따라서, 훗날 버전과 수정 순서를 헷갈리는 불상사를 막기 위해 버전을 명시하는 것이 좋을 것 같습니다. (ex. 버튼음_ver.1_1)

**Comment by ywj58** [comment]
넵

**Comment by Lesin928** [comment]
기획 건의사항 반영해서 한번 더 확인 부탁드립니다~

**Comment by LEI-2812** [comment]
사운드 건의사항대로 수정 완료했습니다

**Comment by Lesin928** [comment]
이슈 재업로드로 인해 클로즈합니다.
