### ISSUE TITLE
2021.06.20 [김지현] [양원준] - 게임 UI 피드백

### ISSUE THREAD

**Issue by LEI-2812** [m48483/SocializerRepo#39]
📢 마감일 : 6월 22일
◾ '대화화면' UI 피드백
◾ 기획이 이슈 코멘트란에 피드백 후 그래픽이 확인 코멘트 남기기

**Comment by jjihn** [comment]
대화 카운트는 무늬 없이 단 색깔로만 이루어졌으면 합니다. 
폰트는 동글동글한 글씨체보다는 명조나 고딕체같이 딱딱한 글씨체가 더 게임에 잘 어울릴 것 같습니다.

**Comment by ywj58** [comment]
수정하겠습니다

**Comment by ywj58** [comment]
수정해서 올렸습니다.

**Comment by jjihn** [comment]
앞으로도 텍스트가 있는 경우 폰트는 명조나 고딕으로 통일해서 작업 부탁드립니다.
