### ISSUE TITLE
2021.07.10 [이승민] - 작업물 이름 변경

### ISSUE THREAD

**Issue by Lesin928** [m48483/SocializerRepo#54]
📢 마감일 : 없음 (상시로 확인)

작업물 폴더가 세분화 되었습니다.
-사운드, 그래픽별로 source 폴더 추가
-UI 폴더 세분화 (결과창, 대화 밖, 대화창)
-작업물 이름 변경 이슈 재업로드

◾이전 이슈부터 강조드린 **변경사항 있을시 파일 완전 삭제후 이름 변경하여 다시 업로드** 가 지켜지지 않고 있습니다. EX) 이름_1_1, 이름_1_2, 이름_1_3과 같이 수정횟수만 다른 파일이 존재함.
깃허브는 깃에 올린 파일이 삭제되더라도 원하는 커밋 버전의 파일을 불러오기가 가능합니다. 파일 수정 혹은 재업로드 시에 기존 파일은 부담없이 삭제하시길 바랍니다.

◾ 이름 변경 이후 커밋시에 커밋메세지를 다음과같이 작성 해주시길 바랍니다.

EX) Summary : 그래픽_UI_작업물 이름변경
Description : a, b을 a_1_1, b_2_1로 변경
형식
-이름_버전_수정횟수

◾ 작업물 명명이 미완료된 사항은 아래와 같습니다. 미변경 사유가 있거나 변경이 완료되면 커밋 후 해당 이슈에 **코멘트** 부탁드립니다.
- 그래픽 배경화면 -> 작업물 이름에 버전만 명시되어있고, 수정횟수는 명시되지 않음.
- 그래픽 NPC -> 프랜시스 버전 1 파일이 두개임 (수정횟수 낮은 파일을 삭제 혹은, 다른 버전으로 이름수정)
- 그래픽 UI -> 같은 버전의 파일 다수. (수정횟수 낮은 파일을 삭제 혹은 다른 버전으로 이름 수정)
- 사운드 -> 이름변경 미완료 ex) 프롤로그.mp3 , 작업물 명명이 통일되지 않음.

**Comment by Mepalo** [comment]
프랜시스 파일 수정 완료했습니다.

**Comment by hor5085** [comment]
완료했습니다

**Comment by LEI-2812** [comment]
완료했습니다

**Comment by ywj58** [comment]
완료했습니다
