### ISSUE TITLE
2021.07.10 [이승민] - 원본 파일 업로드

### ISSUE THREAD

**Issue by Lesin928** [m48483/SocializerRepo#55]
📢 마감일 : 7월 18일

각 작업자 workpiece에 원본 파일 폴터 source가 추가되었습니다.

이제 아트 파트 작업자 여러분께서는 작업물 파일만이 아닌 해당 작업물의 원본 파일까지 
해당 폴더에 업로드 부탁드립니다.
업로드가 완료되면 코멘트 부탁드립니다.

-원본 파일 이란? 
작업물을 수정할수 있는 형태의 파일 (예시로 캔버스파일, clip파일, 포토샵에서의 PNG 파일 등등) 
사운드의 경우 작업물 파일은 하나의 음악이나, 원본 파일 여라가지 효과음이 나뉘어진 파일이고, 
그래픽의 경우 작업물 파일은 하나의 이미지이나, 원본 파일은 명암, 질감, 선, 채색 등등의 레이어가 나뉘어진 파일이다. (이해를 돕기위한 설명이므로 실제와 다를 수 있습니다.)

-원본 파일을 올리는 이유 
깃을 사용하는 큰 세가지 이유는 버전관리와 백업, 협업이다.
원본 파일의 버전관리가 되어야 수정시 용이하다.
작업물 수정시 작업물 파일이 아닌 원본파일을 이용해 수정하기 떄문에 원본 파일을 백업해놔야 한다. (원본 파일이 사라질 시에 작업물 파일을 수정해야 하는 사태가 벌어짐)
원본 파일 없이 작업물만 올리는 형태는 소스코드와 에셋, 프로젝트파일 없이 빌드된 게임만 깃에 올리는것과 같음.

-원본 파일 저장 주의점
원본 파일은 해당 파일의 작업물과 버전을 달리함. (작업물은 유의미한 수정시에 올리면서 수정하나, 원본은 수시로 바뀌어짐) 
작업시에 꼭, **깃에 올라와 있는 원본 파일을 가지고 작업할 것.** 작업 이후 이름을 변경하면서 깃에 커밋해야 하는데, 다른 경로에서 수정할 경우 깃에는 변경사항이 없어 커밋을 잊을 수 있음.

원본 파일 저장 형식 EX) 이름(원본)_버전_수정횟수 (작업물과 같으나, 이름 뒤에 **원본**을 추가)

**Comment by hor5085** [comment]
완료했습니다

**Comment by LEI-2812** [comment]
완료했습니다

**Comment by Mepalo** [comment]
완료했습니다

**Comment by ywj58** [comment]
완료했습니다.
