### ISSUE TITLE
2021.07.18 [박우영] - 배경 '타이틀 화면'

### ISSUE THREAD

**Issue by LEI-2812** [m48483/SocializerRepo#62]
📢 마감일 : 8월 22일
◾ 배경 '타이틀화면' 작업
◾ 자유롭게 작업한 뒤 8월 22일까지 업로드
◾ 최소 2개 정도의 분위기가 다른 작업물을 완성하면 더 좋음 (권장사항일 뿐, 이대로 하지 않아도 됨)
✔ 참고 자료 경로 : Documents > graphic > bg > '20200928 Socializer 컨셉, NPC, 세부 기획.pdf'

**Comment by hor5085** [comment]
확인했습니다

**Comment by LEI-2812** [comment]
[2021.08.01] 같은 내용 공지 완료

**Comment by LEI-2812** [comment]
[2021.08.15] 같은 내용 공지 완료
