### ISSUE TITLE
2021.08.15 [김지현] [양원준] - UI 피드백 (08.22 생성)

### ISSUE THREAD

**Issue by LEI-2812** [m48483/SocializerRepo#85]
📢 마감일 : 8월 29일
◾ '캐릭터 생성' ui 피드백
◾ 기획이 이슈 코멘트란에 피드백 후 그래픽이 확인 코멘트 남기기

**Comment by LEI-2812** [comment]
8월 15일에 올려야 하는 피드백이었는데 제때 올리지 못했습니다. 죄송합니다.
기간은 '보고서' ui 피드백과 같이 8월 29일까지입니다.

**Comment by jjihn** [comment]
이름 칸 반투명하게 변경 가능하신가요? 변경 가능하다면 대화창 정도 투명도면 될 거 같아요.

**Comment by ywj58** [comment]
수정했습니다.
