### ISSUE TITLE
2021.09.12 [김지현] [양원준] - 배경 피드백

### ISSUE THREAD

**Issue by LEI-2812** [m48483/SocializerRepo#91]
📢 마감일 : 9월 19일
◾ '게임 메뉴' ui 피드백
◾ 기획이 이슈 코멘트란에 피드백 후 그래픽이 확인 코멘트 남기기

**Comment by jjihn** [comment]
메뉴 배경창 대화창처럼 반투명하게 가능한가요??

**Comment by LEI-2812** [comment]
마감일 10월 3일로 변경

**Comment by ywj58** [comment]
전에 대화창을 해봤는데 회의때 보니까 저만 투명하게 나오고 업로드하면 투명 적용이 안되는거 같습니다
